version: 1

checkmarx:
  scan:
    configs:
      sast:
        incremental: "false"
        filter: "!node_modules,!dist,!build,!coverage"
        lightQueries: "false"
        languageMode: "multi"
        baseBranch: "main"
        fastScanMode: "true"
        incrementalChangeThreshold: "10"
        presetName: "Checkmarx Default"
        incrementalInBranch: "true"
        defaultConfigId: ""
        engineVerbose: "false"
        recommendedExclusions: "true"
   

      sca:
        LastSastScanTime: "1"
        vulnerabilityComparisonMode: "Branch-Based"
        filter: "*.java,*.js,*.ts,package.json,package-lock.json"
        ExploitablePath: "true"
        javaLanguageVersion: "25"
        pythonLanguageVersion: "3.13"
        enableContainersScan: "false"
        sbom: "false"

      kics:
        filter: "!node_modules,!dist,!build"
        platforms: "Dockerfile,Kubernetes,Terraform,CloudFormation"
        presetId: "f22bffe9-627b-498f-8161-11d636e97beb"

      containers:
        imagesFilter: ""
        filesFilter: "!node_modules,!dist,!build"
        packagesFilter: ""
        nonFinalStagesFilter: "false"

      apisec:
        swaggerFilter: "*.json,*.yaml"

      microengines:
        gitCommitHistory: "true"

      aisc:
        filter: "*.java,*.js,*.ts,package.json,package-lock.json"

      plugins:
        ideScans: "false"
        aiGuidedRemediation: "true"
